apiVersion: v1
kind: Namespace
metadata:
  name: transit-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transit-scraper
  annotations:
    iam.gke.io/gcp-service-account: transit-scraper@zeitgeistlabs.iam.gserviceaccount.com
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-scratch
  namespace: transit-data
  annotations:
    pv.kubernetes.io/gid: "2001"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: transit-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      priorityClassName: production-critical
      serviceAccountName: transit-scraper
      securityContext:
        fsGroup: 2001
      containers:
      - name: scraper
        image: us.gcr.io/zeitgeistlabs/transit-scraper:TAG
        imagePullPolicy: Always
        args:
          - scraper
          - --config
          - /config/production.json 
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 512Mi
        volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
            readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: scraper-scratch
        - name: config
          secret:
            secretName: transit-scraper-config